version: '3'
services:
  app:
    image: rahulkumarpaswan/${IMAGE_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
