variable "env_prefix" {}
variable "db_instance_identifier" {}
variable "db_allocated_storage" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_multi_az" {}
variable "db_backup_retention_period" {}
variable "subnet_id_1" {}
variable "subnet_id_2" {}
variable "vpc_id" {}
variable "my_security_group_id" {}